kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  namespace: "hello-openshift-04"
  labels:
    type: local
    app: ftp-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"