apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: task-pv-volume
      mountPath: /data
  volumes:
  - name: task-pv-volume
    persistentVolumeClaim:
      claimName: task-pv-claim